/**
 * Converts raw Google Drive URLs (generated by Google Forms and stored in Google Sheets)
 * into Google's ultra-fast User Content CDN endpoints (lh3.googleusercontent.com).
 *
 * Appending `=w{width}-h{height}-c` instructs Google's edge servers to compress
 * and resize on the fly, converting heavy 8–15MB smartphone photos into lightweight WebP/JPEGs.
 */
export function formatDriveUrl(rawUrl?: string, width = 1200, height = 800): string {
  if (!rawUrl) return "";
  const trimmed = rawUrl.trim();
  if (!trimmed) return "";

  // Non-drive URLs (e.g. Unsplash or local static files in /public)
  if (
    trimmed.startsWith("/") ||
    (trimmed.startsWith("http") && !trimmed.includes("drive.google.com") && !trimmed.includes("googleusercontent.com"))
  ) {
    return trimmed;
  }

  // Extract file ID from drive.google.com/open?id=ID, drive.google.com/file/d/ID/..., or raw ID
  const idMatch =
    trimmed.match(/[?&]id=([-\w]{20,})/) ||
    trimmed.match(/\/d\/([-\w]{20,})/) ||
    trimmed.match(/[-\w]{25,}/);

  const fileId = idMatch ? idMatch[1] || idMatch[0] : null;

  if (fileId) {
    return `https://lh3.googleusercontent.com/d/${fileId}=w${width}-h${height}-c`;
  }

  return trimmed;
}
